# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: 'Linux-Python 3.8', python: '3.8', os: ubuntu-latest}
          - {name: 'Linux-Python 3.7', python: '3.7', os: ubuntu-latest}
          - {name: 'Linux-Python 3.6', python: '3.6', os: ubuntu-latest}
          - {name: 'Mac-Python 3.8', python: '3.8', os: macos-latest}
          - {name: 'Mac-Python 3.7', python: '3.7', os: macos-latest}
          - {name: 'Mac-Python 3.6', python: '3.6', os: macos-latest}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install -U wheel
        pip install -U setuptools
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install click
        pip install --editable .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Create example folders in Github Actions VM
      run: |
        mkdir myproject
        echo "from flask import Flask
          app = Flask(__name__)

          @app.route('/')
          def hello_world():
            return 'Hello, World!'" >> myproject/app.py
        cd myproject
        pwd
        cd ..
        pwd
        mkdir myproject2
        echo "from flask import Flask
          app = Flask(__name__)

          @app.route('/')
          def hello_world():
            return 'Hello, World!'" >> myproject2/app.py 
        echo "{
          "type": "python",
          "command": "flask run"
        }" >> myproject2/af-config.json
        cd myproject2
        pwd
        cd ..
        pwd
    - name: Run test script
      run: pytest ./tests/tests.py -vv

      
